# Path to my oh-my-zsh installation.
export ZSH=/Users/jordan/.oh-my-zsh

# Enable additional glyphs in Awesome-TerminalFont's special character set.
# https://github.com/bhilburn/powerlevel9k/wiki/Install-Instructions#option-3-install-awesome-powerline-fonts
POWERLEVEL9K_MODE='awesome-patched'

# Set name of the theme to load. Optionally, if you set this to "random"
# it'll load a random theme each time that oh-my-zsh is loaded.
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
ZSH_THEME="powerlevel9k/powerlevel9k"

# Powerlevel9k config.
POWERLEVEL9K_PROMPT_ON_NEWLINE=true
POWERLEVEL9K_PROMPT_ADD_NEWLINE=true
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(dir vcs background_jobs)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status time)
POWERLEVEL9K_SHORTEN_STRATEGY="truncate_middle"
POWERLEVEL9K_SHORTEN_DIR_LENGTH=3

# Gruvbox colours for Powerlevel9k.
# Based on https://github.com/bhilburn/powerlevel9k/wiki/Show-Off-Your-Config#miguelcaraxs-configuration.
POWERLEVEL9K_DIR_HOME_BACKGROUND='09'
POWERLEVEL9K_DIR_DEFAULT_BACKGROUND='09'
POWERLEVEL9K_DIR_HOME_SUBFOLDER_BACKGROUND='009'
POWERLEVEL9K_DIR_HOME_FOREGROUND='236'
POWERLEVEL9K_DIR_DEFAULT_FOREGROUND='236'
POWERLEVEL9K_DIR_HOME_SUBFOLDER_FOREGROUND='236'

POWERLEVEL9K_VCS_GIT_GITHUB_ICON='\uE1AA'
POWERLEVEL9K_VCS_CLEAN_BACKGROUND='236'
POWERLEVEL9K_VCS_CLEAN_BACKGROUND='119'
POWERLEVEL9K_VCS_CLEAN_FOREGROUND='236'
POWERLEVEL9K_VCS_UNTRACKED_BACKGROUND='214'
POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND='236'
POWERLEVEL9K_VCS_MODIFIED_BACKGROUND='196'
POWERLEVEL9K_VCS_MODIFIED_FOREGROUND='236'

POWERLEVEL9K_BACKGROUND_JOBS_FOREGROUND='236'
POWERLEVEL9K_BACKGROUND_JOBS_BACKGROUND='220'

# Uncomment the following line to use hyphen-insensitive completion. Case
# sensitive completion must be off. _ and - will be interchangeable.
HYPHEN_INSENSITIVE="true"

# Uncomment the following line to display red dots whilst waiting for completion.
COMPLETION_WAITING_DOTS="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git zsh-completion zsh-syntax-highlighting)

source $ZSH/oh-my-zsh.sh

# User configuration

export MANPATH="/usr/local/man:$MANPATH"

# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='vim'
else
  export EDITOR='mvim'
fi

# Compilation flags
export ARCHFLAGS="-arch x86_64"

# ssh
export SSH_KEY_PATH="~/.ssh/rsa_id"

# For convenience when working with Go.
export GOPATH=$(go env GOPATH)
export PATH=$PATH:$(go env GOPATH)/bin

# For adb.
 if [ -d "$HOME/adb-fastboot/platform-tools" ] ; then
     export PATH="$HOME/adb-fastboot/platform-tools:$PATH"
 fi

 # For GNU coreutils and man pages.
export PATH="/usr/local/opt/coreutils/libexec/gnubin:$PATH"
export MANPATH="/usr/local/opt/coreutils/libexec/gnuman:$MANPATH"

# Aliases.
alias ls="ls --color=always"
alias grep="grep --color=always"
alias vim="/usr/local/bin/vim" # Mac's built-in Vim doesn't have clipboard support.

# Directory colors.
# Disabled because the solarized colours don't complement gruvbox.
# eval `dircolors ~/.dir_colors`

# Set up ANDROID_HOME env var for Android Studio.
export ANDROID_HOME=${HOME}/Library/Android/sdk
export PATH=${PATH}:${ANDROID_HOME}/tools
export PATH=${PATH}:${ANDROID_HOME}/platform-tools

# added by Anaconda3 4.3.1 installer
export PATH=${PATH}:/Users/jordan/anaconda3/bin

# For Apache Spark.
export PATH=${PATH}:${HOME}/spark-2.1.1-bin-hadoop2.7/bin
export PYSPARK_DRIVER_PYTHON=ipython3

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/jordan/google-cloud-sdk/path.zsh.inc' ]; then source '/Users/jordan/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/Users/jordan/google-cloud-sdk/completion.zsh.inc' ]; then source '/Users/jordan/google-cloud-sdk/completion.zsh.inc'; fi
