#!/bin/bash

# For GNU coreutils and man pages.
export PATH="/usr/local/opt/coreutils/libexec/gnubin:$PATH"
export MANPATH="/usr/local/opt/coreutils/libexec/gnuman:$MANPATH"

if [ -f ~/.bash_prompt ]; then . ~/.bash_prompt; fi
