#!/bin/bash

# macOS sources .bash_profile for every new window/tab,
# so it's preferrable over .bashrc.

# For GNU coreutils and man pages.
export PATH="/usr/local/opt/coreutils/libexec/gnubin:$PATH"
export MANPATH="/usr/local/opt/coreutils/libexec/gnuman:$MANPATH"

if [ -f ~/.bash_prompt ]; then . ~/.bash_prompt; fi

# Aliases.
eval "$(thefuck --alias)"
alias ls="ls --color=always"
alias grep="grep --color=always"
alias vim="/usr/local/bin/vim" # Mac's built-in Vim doesn't have clipboard support.

# Directory colors.
eval `dircolors ~/.dir_colors`

# For bash autocompletion.
if [ -f $(brew --prefix)/etc/bash_completion ]; then
    . $(brew --prefix)/etc/bash_completion
fi

# Set up ANDROID_HOME env var for Android Studio.
export ANDROID_HOME=${HOME}/Library/Android/sdk
export PATH=${PATH}:${ANDROID_HOME}/tools
export PATH=${PATH}:${ANDROID_HOME}/platform-tools

# For convenience when working with Go.
export PATH=${PATH}:${GOPATH}/bin

# added by Anaconda3 4.3.1 installer
export PATH=${PATH}:/Users/jordan/anaconda3/bin

# For Apache Spark.
export PATH=${PATH}:${HOME}/spark-2.1.1-bin-hadoop2.7/bin
export PYSPARK_DRIVER_PYTHON=ipython3

# For mySQL.
export=PATH${PATH}:/usr/local/mysql/bin

